version = 0.1

[default.deploy.parameters]
stack_name = ""
resolve_s3 = true
s3_prefix = ""
region = ""
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" LangfuseHost=\"https://cloud.langfuse.com\""
image_repositories = []

[default.global.parameters]
region = ""
